![](imgs/Advanced_numpy_cover.png)

# Numpy arrays
**1D-arrays**

In [1]:
import numpy as np

In [2]:
# Zeros array


In [3]:
# Ones array


# Numpy arrays
**1D-arrays**

In [4]:
# Sequence


In [5]:
# Sequence: arange(start, stop, step). Default: start=0 & step=1


In [6]:
# Random


![Slide1DArrays](imgs/make_1d_arrays.png)

# Numpy arrays
**2D-arrays**

In [7]:
# Zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Random
np.random.randint(0, 10, (2, 3))

array([[2, 6, 3],
       [5, 9, 5]])

# Numpy arrays
**2D-arrays**

In [10]:
# Sequences


In [11]:
# More sequences (dense meshgrids)


In [12]:
# More sequences (open meshgrids)


# Lists vs numpy arrays
**What is a list?**

In [13]:
my_list = [5, "string", 3.5, ('tu', 'ple')]
my_list

[5, 'string', 3.5, ('tu', 'ple')]

![memory_lists1](imgs/memory_layout_list_array_1b.png)

# Lists vs numpy arrays
**What is a list?**

In [14]:
my_list = [5, "string", 3.5, ('tu', 'ple')]

![memory_lists2](imgs/memory_layout_list_array_2b.png)

# Lists vs numpy arrays
**What is a list?**

In [15]:
my_list = [5, "string", 3.5, ('tu', 'ple')]

![memory_lists3](imgs/memory_layout_list_array_3b.png)

# Lists vs numpy arrays
**And an array?**

In [16]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

![memory_lists4](imgs/memory_layout_array3.png)

# Lists vs numpy arrays
**Indexing in lists**

Lists can be indexed with a single number:

In [17]:
my_list = [i for i in range(9)]  # List comprehension
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [18]:
print(my_list[3])

3


# Lists vs numpy arrays
**Indexing in arrays**

So do arrays:

In [19]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
my_array[3]

3

# Lists vs numpy arrays
**So why using arrays?**

Speed matters: We compare math package functions on lists, **with a list comprehension**, and with numpy universal functions (ufunc)

In [21]:
import math
import random
import timeit

In [22]:
def compute_square_root(x):
    y = np.empty(len(x))
    for i in range(len(y)):
        y[i] = math.sqrt(x[i])
        
    return y

# List of random numbers
x = [random.randint(1, 100) for i in range(10000)]

In [23]:
%timeit compute_square_root(x)

1.46 ms ± 27.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Now we do the same but using **numpy universal functions (ufunc)**

In [24]:
x = np.array(x)

%timeit np.sqrt(x)

14.9 µs ± 332 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
