![](../imgs/Advanced_numpy_cover.png)

# Numpy arrays
**1D-arrays**

In [1]:
import numpy as np

In [2]:
# Zeros array
np.array([0,0,0,0,0,0.,0,0,0,0])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# Zeros array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Ones array
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Numpy arrays
**1D-arrays**

In [5]:
# Sequence
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Sequence: arange(start, stop, step). Default: start=0 & step=1
np.arange(9, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [7]:
# Random
np.random.randint(0, 10, 10)

array([9, 8, 4, 8, 9, 8, 7, 6, 5, 7])

![Slide1DArrays](../imgs/make_1d_arrays.png)

# Numpy arrays
**2D-arrays**

In [8]:
# Zeros
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
# Ones
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
# Random
np.random.randint(0, 10, (2, 10))

array([[5, 4, 7, 5, 5, 2, 7, 2, 3, 5],
       [4, 9, 8, 6, 1, 3, 3, 7, 1, 0]])

# Numpy arrays
**2D-arrays**

In [11]:
# Sequences
np.arange(2 * 10).reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [12]:
# More sequences (open meshgrids)
x,y = np.ogrid[0:2, 0:10]
x

array([[0],
       [1]])

In [13]:
y

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
x+y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [15]:
# More sequences (dense meshgrids)
x, y = np.mgrid[0:2, 0:10]
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [16]:
y

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [17]:
x+y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

# Lists vs numpy arrays
**What is a list?**

In [18]:
my_list = [5, "string", 3.5, ('tu', 'ple')]
my_list

[5, 'string', 3.5, ('tu', 'ple')]

![memory_lists1](../imgs/memory_layout_list_array_1b.png)

# Lists vs numpy arrays
**What is a list?**

In [19]:
my_list = [5, "string", 3.5, ('tu', 'ple')]

![memory_lists2](../imgs/memory_layout_list_array_2b.png)

# Lists vs numpy arrays
**What is a list?**

In [20]:
my_list = [5, "string", 3.5, ('tu', 'ple')]

![memory_lists3](../imgs/memory_layout_list_array_3b.png)

# Lists vs numpy arrays
**And an array?**

In [21]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

![memory_lists4](../imgs/memory_layout_array3.png)

# Lists vs numpy arrays
**Indexing in lists**

Lists can be indexed with a single number:

In [22]:
my_list = [i for i in range(9)]  # List comprehension
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [23]:
print(my_list[3])

3


# Lists vs numpy arrays
**Indexing in arrays**

So do arrays:

In [24]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
my_array[3]

3

# Lists vs numpy arrays
**So why using arrays?**

Speed matters: We compare a math package function applied on **lists** vs the corresponding numpy universal functions (ufunc)

In [26]:
import math
import timeit

In [27]:
def compute_square_root(x):
    y = np.empty(len(x))
    for i in range(len(y)):
        y[i] = math.sqrt(x[i])
        
    return y

# List of numbers
x = list(np.random.randint(1, 100, 100000))


In [28]:
%timeit compute_square_root(x)

16.6 ms ± 567 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Now we do the same but using **numpy universal functions (ufunc)**

In [29]:
x = np.array(x)

%timeit np.sqrt(x)

126 µs ± 1.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
